modLoader="javafml"
loaderVersion="[32,]"
logoFile="logo.png"
authors="bageldotjpg & Endergized"
credits="Pugz & Farcr"
license="https://github.com/minecraftabnormals/Bamboo-Blocks/blob/master/LICENSE.txt"

[[mods]]
    modId="bamboo_blocks"
    version="${file.jarVersion}"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!'''

[[dependencies.bamboo_blocks]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bamboo_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bamboo_blocks]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"
