modLoader="javafml"
loaderVersion="[31,]"
logoFile="logo.png"
authors="Pugz & bageldotjpg"
credits="*Endergized*, Farcr, Rohan, László Gaming, ʟᴇᴍᴏɴ, Wolftopia, ilja615, Ønelix, Kicsivazz, Axoladdy, TitaniumBrain, and qsefthuopq"

[[mods]]
    modId="bambooblocks"
    version="1.2.11"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!
    '''