modLoader="javafml"
loaderVersion="[31,]"
logoFile="logo.png"
authors="Pugz & bageldotjpg"
credits="*Endergized*, Farcr, Rohan, László Gaming, ʟᴇᴍᴏɴ, Wolftopia, ilja615, Ønelix, Kicsivazz, Axoladdy, TitaniumBrain, and qsefthuopq"

[[mods]]
    modId="bambooblocks"
    version="1.3"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!
    '''

[[dependencies.bambooblocks]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="AFTER"
    side="BOTH"
