modLoader="javafml"
loaderVersion="[24,]"
logoFile="logo.png"
authors="Pugz"

[[mods]]
    modId="bambooblocks"
    version="1.2.2"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!
    '''