modLoader="javafml"
loaderVersion="[32,]"
logoFile="logo.png"
authors="bageldotjpg"
credits="Pugz & Endergized"

[[mods]]
    modId="bambooblocks"
    version="${file.jarVersion}"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!'''

[[dependencies.bambooblocks]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bambooblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bambooblocks]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"
