modLoader="javafml"
loaderVersion="[31,]"
logoFile="logo.png"
authors="Pugz & bageldotjpg"
credits="*Endergized*, Farcr, Rohan, László Gaming, ʟᴇᴍᴏɴ, Wolftopia, ilja615, Ønelix, Kicsivazz, Axoladdy, TitaniumBrain, and qsefthuopq"

[[mods]]
    modId="bambooblocks"
    version="1.4.0"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!
    '''

[[dependencies.bambooblocks]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bambooblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bambooblocks]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="AFTER"
    side="BOTH"
