modLoader="javafml"
loaderVersion="[28,]"
logoFile="logo.png"
authors="Pugz"
credits="*Endergized*, Farcr, Rohan, László Gaming, ʟᴇᴍᴏɴ, Wolftopia, ilja615, Ønelix, Kicsivazz, Axoladdy, TitaniumBrain, and qsefthuopq"

[[mods]]
    modId="bambooblocks"
    version="1.2.9b"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!
    '''